config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :party_animals, only: [:index, :show, :update] do
      resources :bookings, only: [:new, :create]
  end
  resources :users, only: [] do
    resources :party_animals, only: :create
  end

  resources :bookings, only: [:destroy, :show ]
  resources :dashboard, only: :show

  resources :users, only: [] do
    resources :bookings, only: :update
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/party_animal.rb
class PartyAnimal < ApplicationRecord

  mount_uploader :image, PhotoUploader

  belongs_to :user
  has_many :bookings
  validates :party_name, uniqueness: true
  validates :party_name, presence: true
  serialize :category, Array
  serialize :available_dates
end

app/controllers/party_animals_controller.rb
class PartyAnimalsController < ApplicationController
  def index
    if params[:location].blank?
      @party_animals = PartyAnimal.all
    else
      @party_animals = PartyAnimal.where("location ILIKE ? AND NOT user_id=?", "%#{params[:location]}%", current_user)
      # @party_animals = PartyAnimal.where(location: params[:location].capitalize)
    end
  end

  def show
    @party_animal = PartyAnimal.find(params[:id])
  end

  def create
    @party_animal = PartyAnimal.new(party_animal_params)
    @party_animal.user = current_user
    if @party_animal.save!
      redirect_to dashboard_path(current_user)
    else
      # HERE SHOULD BE SOMETHING ELSE -P
      redirect_to dashboard_path(current_user)
    end
  end

  private

  def party_animal_params
    params.require(:party_animal).permit(:image, :location, :availability, :party_name, :available_dates, :photo_cache, :description)
  end
end

app/views/party_animals/index.html.erb
<div class="container">
  <div class="party-animals-header">
  <% if params[:location].present? %>
    <h1>Party Animals in <%= params[:location].capitalize %> </h1>
  <% end %>
</div>
  <div class="page-header">
    <form class="form-inline" action="/party_animals" method="get" style="display: inline">
      <div class="form-group mx-sm-3 mb-2">
        <label for="insert-city" class="sr-only">Search</label>
        <input  name="location" type="text" class="form-control" placeholder="Search for your city">
          <%= link_to "Let's go", party_animals_path, class: "btn btn-flat" %>
      </div>
    </form>
  </div>

    <div class="cards">
      <% @party_animals.each do |party_animal| %>
        <%= link_to party_animal_path(party_animal) do%>
          <%= render 'shared/card',  pa: party_animal  %>
          <% end %>
      <% end %>
    </div>
   </div>
</div>

<!-- <div></div> -->

app/views/party_animals/show.html.erb
<div class="container">
  <h3><%= @party_animal.party_name %></h3>
  <div class="tag-container">
    <% @party_animal.category.each do |tag| %>
      <div class="tag"><%= tag %></div>
    <% end %>
  </div>

<%= render 'shared/blog-card',  pa: @party_animal  %>