config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :party_animals, only: [:index, :show, :update] do
      resources :bookings, only: [:new, :create]
  end
  resources :users, only: [] do
    resources :party_animals, only: :create
  end

  resources :bookings, only: [:destroy, :show ]
  resources :dashboard, only: :show

  resources :users, only: [] do
    resources :bookings, only: :update
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show

    @bookings = Booking.where(user_id: current_user.id)
    @party_animal = PartyAnimal.new
    @invitations = Booking.where(party_animal_id: current_user.party_animal)
  end


end

app/views/dashboard/show.html.erb
<div class='container' id="container">
    <div class='row'>
        <div class="col-xs-12">
            <%= render 'shared/blog-card2',  pa: current_user%>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <% unless current_user.party_animal %>
            <h1>Become a Party Animal</h1>
            <%= simple_form_for([current_user, @party_animal]) do |f| %>
            <%= f.input :party_name, class: "form-control" %>
            <%= f.input :location %>
            <%= f.input :available_dates %>
            <%= f.input :image %>
            <%= f.input :image_cache, as: :hidden %>
            <%= f.input :description %>
            <%= f.button :submit, class: "btn btn-success" %>
            <% end %>
            <% end %>
            <% if current_user.party_animal %>
            <%= render 'shared/blog-card',  pa: current_user.party_animal%>
            <% end %>
        </div>
        <div class="booking-div">
            <h3>These are the invitations from the people who would love to party with you:</h3>
            <ol>
                <% @invitations.each do |invitation| %>
                <li>
                    You have an invitation from <strong>
                        <%= invitation.user.first_name + " " + invitation.user.last_name %></strong> on: <strong>
                        <%= invitation.date.strftime('%A, %b %d') %></strong>
                    <% if invitation.confirmed %>
                    <p>Accepted</p>
                    <% else %>
                    <%= link_to "Accept this invitation", user_booking_path( current_user ,invitation), data: { confirm: 'Are you sure?', }, class: "btn btn-success", method: :patch %>
                    <% end %>
                    <% if invitation.confirmed%>
                    <p>Declined</p>
                    <% else %>
                    <%= link_to "Decline this invitation", user_booking_path( current_user ,invitation), data: { confirm: 'Are you sure?', }, class: "btn btn-danger", method: :patch %>
                    <% end %>
                </li>
                <% end %>
            </ol>
        </div>
        <div>
            <%= link_to 'Homepage', root_path, class: "btn btn-info"  %>
            <%= link_to 'Party Animals', party_animals_path, class: "btn btn-info"  %>
        </div>
    </div>