config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :party_animals, only: [:index, :show, :update] do
      resources :bookings, only: [:new, :create]
  end
  resources :users, only: [] do
    resources :party_animals, only: :create
  end

  resources :bookings, only: [:destroy, :show ]
  resources :dashboard, only: :show

  resources :users, only: [] do
    resources :bookings, only: :update
  end

end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_blog-card.html.erb
<div class="blog-card">
    <div class="meta">
      <div class="photo">
          <%= cl_image_tag(pa.image, width: 400, heigth: 400) %>
      </div>
    </div>
    <div class="description">
      <% if pa.user == current_user %>
        <p>This is your PartyAnimal</p>
      <% else %>
        <h1>Party with <%= pa.party_name %></h1>
      <% end %>
        <h2>One of the wildest partyanimals in <%= pa.location %></h2>

      <p><%= pa.description %></p>

      <% if current_user.nil? == false %>
        <% if current_user.party_animal.nil? || current_user.party_animal.id  != pa.id %>
          <p class="read-more">
            <%= link_to "Invite #{pa.party_name} to party", new_party_animal_booking_path(pa)%>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/shared/_blog-card2.html.erb
<div class="blog-card2">
    <div class="description">
        <p>Welcome, <%= current_user.first_name + " " + current_user.last_name %>
        </p>
        <h2>Ready to have a party?</h2>
        <% if current_user.bookings.blank? %>
          <p>For the moment you have not sent any invitations to our party animals</p>
        <% else %>

          <div>
              <p>These are the invitations you have sent:</p>
              <ol>
                  <% @bookings.each do |booking| %>
                  <li>You have a booking with <strong>
                          <%= booking.party_animal.party_name %></strong>
                      on
                      <%= booking.date.strftime('%A, %b %d') %>
                      <%= link_to "Cancel booking", booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"%>
                      <% if booking.confirmed == nil %>
                      <p>Status: <em>Pending</em></p>
                      <% elsif booking.confirmed? == true %>
                      <p>Status: <em>Accepted</em></p>
                      <% else %>
                      <p>Status:<em>Declined</em></p>
                      <% end %>
                  </li>
                  <% end %>
              </ol>
              <% end %>
           </div>
    </div>

        <div class="meta">
            <div class="photo">
                <%= cl_image_tag(pa.image, width: 400, heigth: 400) %>
            </div>
        </div>
</div>

app/views/shared/_card.html.erb
<!-- <div class="card-category">
  <%#= cl_image_tag(pa.image, gravity: "faces", crop: "fill") %>
  <p><%#= pa.party_name %></p>
</div> -->


<div class="card-polaroid", polaroid-caption=<%= pa.party_name %>>
  <%= cl_image_tag(pa.image, width: 250, height: 250, gravity: "faces", crop: "fill") %>
  <p class="pa-name"><%= pa.party_name %></p>
</div>

<!-- <div class="card-category"> -->
  <%#= cl_image_tag(pa.image, width: 380, height: 300, gravity: "faces", crop: "fill") %>
  <!-- <p><%= pa.party_name %></p> -->
<!-- </div> -->

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo      -->
  <a href="/party_animals" i class="far fa-smile-wink" id="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% unless user_signed_in? %>
    <!-- <a href="" class="btn-treehouse">Register</a> -->
    <li><%= link_to 'Register', new_user_registration_path, class: "btn-treehouse"  %></li>
    <!-- <a href="" class="navbar-wagon-item navbar-wagon-link">Login</a> -->
    <li><%= link_to 'Log in', user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
    <% end %>

    <!-- Profile picture with dropdown list -->
          <% if user_signed_in? %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= cl_image_tag(current_user.image, id: "navbar-wagon-menu", class: "avatar dropdown-toggle", data: { toggle: "dropdown" }) %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <!-- <li><a href="#">Profile</a></li> -->
          <li><%= link_to 'Profile', dashboard_path(current_user) %></li>
          <!-- <li>
            <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>
          </li> -->
          <!-- <li><a href="#">Log Out</a></li> -->
          <li><%= link_to 'Log out',  destroy_user_session_path, method: :delete  %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
       <!--  <li><a href="#">Register</a></li> -->
       <% unless user_signed_in? %>
       <li><%= link_to 'Register', new_user_registration_path  %></li>
        <!-- <li><a href="#">Login</a></li> -->
        <li><%= link_to 'Log in', user_session_path  %></li>
        <% end %>
         <% if user_signed_in? %>
        <li><a href="#">Messages</a></li>
        <li><%= link_to 'Profile', dashboard_path(current_user) %></li>
        <li><%= link_to 'Log out',  destroy_user_session_path, method: :delete  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>